version: 2.1
executors:
  default-executor:
    working_directory: ~/
    shell: /bin/bash
    docker:
      - image: circleci/openjdk:8-jdk

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: ~/
    paths:
      - repo

attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/

jobs:
   setup_prerequisites:
      executor: default-executor
      steps:
         - run:
            working_directory: ~/repo
            command: |
               git clone https://github.com/swapnilpingle89/zm-soap-harness.git ~/repo/zm-soap-harness
               git clone https://github.com/Zimbra/zm-zcs.git ~/repo/zm-zcs
               git clone https://github.com/Zimbra/zimbra-package-stub.git ~/repo/zimbra-package-stub
               git clone https://github.com/Zimbra/zm-mailbox.git ~/repo/zm-mailbox
               mkdir -p /home/circleci/repo/.zcs-deps
               mkdir -p /home/circleci/repo/.ivy2/cache
               sudo apt-get update; sudo apt-get install ant-contrib;
               cd ./zm-mailbox
               sudo ant publish-local-all -Dzimbra.buildinfo.version=8.8.0_GA
               sed -i 's/localhost/ec2-13-127-151-6.ap-south-1.compute.amazonaws.com/g' ~/repo/zm-soap-harness/conf/global.properties
               sed -i 's/zimbra.com/ec2-13-127-151-6.ap-south-1.compute.amazonaws.com/g' ~/repo/zm-soap-harness/conf/global.properties
               sudo ant clean build-soap-data-file Execute_Tests -DtestRoot="data/soapvalidator/MailClient/Auth/auth_basic.xml" -Dsuite="smoke"

         - *persist-workspace

workflows :
   version: 2
   main:
      jobs: 
         - setup_prerequisites
