version: 2.1
executors:
  default-executor:
    working_directory: ~/
    shell: /bin/bash
    docker:
      - image: circleci/openjdk:8-jdk

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: ~/
    paths:
      - repo

attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/

jobs:
   clone_repos:
      executor: default-executor
      steps:
         - run:
            working_directory: ~/repo
            command: |
               git clone https://github.com/Zimbra/zm-zcs.git ~/repo/zm-zcs
               git clone https://github.com/Zimbra/zimbra-package-stub.git ~/repo/zimbra-package-stub
               git clone https://github.com/Zimbra/zm-mailbox.git ~/repo/zm-mailbox    
               mkdir -p /home/circleci/.zcs-deps
               mkdir -p /home/circleci/.ivy2/cache
               wget https://files.zimbra.com/repository/ant-contrib/ant-contrib-1.0b1.jar

         - *persist-workspace

   build_dependencies:
      executor: default-executor 
      steps:
         - *attach-workspace
         - run:
            working_directory: ~/repo/zm-mailbox
            command:
               ant publish-local-all -Dzimbra.buildinfo.version=8.8.0_GA
              
   set_test_configs:
       executor: default-executor
       steps:
          - *attach-workspace 
          - checkout
          - run:
             sed -i 's/localhost/ec2-13-127-151-6.ap-south-1.compute.amazonaws.com/g' ~/repo/zm-soap-harness/conf/global.properties
             sed -i 's/zimbra.com/ec2-13-127-151-6.ap-south-1.compute.amazonaws.com/g' ~/repo/zm-soap-harness/conf/global.properties
       
   execute_tests:
      executor: default-executor 
      steps:
         - *attach-workspace
         - run:
             ant clean build-soap-data-file Execute_Tests -DtestRoot="data/soapvalidator/MailClient/Auth/auth_basic.xml" -Dsuite="smoke"

workflows :
   version: 2
   main:
      jobs: 
         - clone_repos
         - build_dependencies :
            requires:
               - clone_repos 
         - set_test_configs :
            requires:
               - build_dependencies 
         - execute_tests :
            requires:
               - set_test_configs  
